server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:h2:mem:auth_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

# Eureka — s'enregistrer auprès du service registry
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Clé secrète JWT — DOIT être identique dans api-gateway
# En production: utiliser une variable d'environnement ${JWT_SECRET}
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.ecommerce.auth: DEBUG
    org.springframework.security: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html